### ISSUE TITLE
Add `NdbStrVariant::as_str` method

### ISSUE THREAD

**Issue by yukibtc** [damus-io/nostrdb-rs#6]
Hey, I'm trying to do some changes/improvements in `rust-nostr` to make it `zero-copy` where possible, in particular for `NostrDatabase::query`.

For `nostrdb` is needed the `NdbStrVariant::as_str` method (currently I'm allocating for serializing the `NdbStrVariant::Id` to a hex string). I tried to implement the `as_str` but the code panic :(

**Comment by jb55** [comment]
I see what you mean now.

`as_str` doesn't really make sense for `NdbStrVariant` (in the `-> &str` sense), because it is not necessarily always a string, when nostrdb detects a 64-char hex string in a tag it will store it directly as non-null-terminated 32 bytes for space savings. since it is not stored as a string there is no way to get a non-copyable string version of the hex, you have to allocate.

**Comment by jb55** [comment]
this saves you from having to do hex serialization all the time when comparing pubkeys against tags, conversion to hex for query filters is not a hot path for us, so allocating is fine in those cases.

**Comment by yukibtc** [comment]
Ok, thanks
